trigger:
- master

pr:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
- group: my-variable-group
- name: my-passed-variable
  value: $[variables.myhello]


steps:

- script: echo $(myhello) # uses macro syntax
- script: echo $(my-passed-variable) 

- task: DotNetCoreCLI@2
  inputs:
    command: run
    projects: "*.csproj"
    arguments: -c $(BuildConfiguration)
  displayName: Build and Run Statiq

- publish: output
  artifact: website
  displayName: Publish Artifacts